global:
  registry: docker.io
image:
  repository: ccloud/vault-tec
  tag: "3b705bcd87afd4ec8553152a686f393b69641cab"
  pullPolicy: IfNotPresent
limits:
  cpu: 200m
  memory: 256Mi
rbac:
  create: true
  serviceAccountName: vault-tec
config:
  approle:
    prefix: vt-generic
    ttl: 48h
    rotate: 24h
  intervals:
    period: 5m
    jitter: 1.1
  concourse:
    url: https://example.com
  vault:
    url: https://example.com
    approleMount: approle
    keyValueMount: kv
    policies:
    - a
    - b
credentials:
  concourse:
    username: concourse-user
    password: pw
  vault:
    username: vault-user
    password: pw
