apiVersion: v1
kind: Secret
metadata:
  name: vault-tec-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  CONCOURSE_USERNAME: {{ required "no concourse.username given" .Values.credentials.concourse.username | quote }}
  CONCOURSE_PASSWORD: {{ required "no concourse.password given" .Values.credentials.concourse.password | quote }}
  VAULT_USERNAME: {{ required "no vault.username given" .Values.credentials.vault.username | quote }}
  VAULT_PASSWORD: {{ required "no vault.password given" .Values.credentials.vault.password | quote }}
