{{- if .Values.glance_nanny.enabled }}
{{- if .Values.glance_nanny.db_purge.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: glance-nanny
  namespace: monsoon3
  labels:
    system: openstack
    service: glance-nanny
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
        component: glance-nanny
  template:
    metadata:
      annotations:
        {{- if and $.Values.global.linkerd_enabled $.Values.global.linkerd_requested }}
        linkerd.io/inject: enabled
        {{- end }}
      labels:
        component: glance-nanny
    spec:
      nodeSelector:
        zone: farm
      volumes:
        - name: glance-scripts
          configMap:
            name: glance-scripts
        - name: glance-etc-confd
          secret:
            secretName: {{ .Release.Name }}-secrets
        - name: glance-etc
          configMap:
            name: glance-etc
      containers:
{{- if .Values.glance_nanny.db_purge.enabled }}
        - name: db-consistency-and-purge
          image: {{ required ".Values.global.registry is missing" .Values.global.registry }}/loci-glance:{{.Values.imageVersionGlanceApi | default .Values.imageVersion | default .Values.image_version | required "Please set glance.imageVersion or similar"}}
          imagePullPolicy: IfNotPresent
          command:
            - dumb-init
            - kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "{{ if not .Values.glance_nanny.debug }}/bin/bash /scripts/glance-db-consistency-and-purge.sh{{ else }}sleep inf{{ end }}"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DEPENDENCY_SERVICE
              value: "glance,glance-mariadb"
            - name: GLANCE_DB_PURGE_ENABLED
              value: {{ .Values.glance_nanny.db_purge.enabled | quote }}
            - name: GLANCE_DB_PURGE_OLDER_THAN
              value: {{ .Values.glance_nanny.db_purge.older_than | quote }}
            - name: GLANCE_DB_PURGE_MAX_NUMBER
              value: {{ .Values.glance_nanny.db_purge.max_number | quote }}
            - name: GLANCE_NANNY_INTERVAL
              value: {{ .Values.glance_nanny.interval | quote }}
            {{- if .Values.sentry.enabled }}
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry
                  key: glance.DSN.python
            {{- end }}
          volumeMounts:
          - name: glance-scripts
            mountPath: /scripts/glance-db-consistency-and-purge.sh
            subPath: glance-db-consistency-and-purge.sh
            readOnly: true
          - name: glance-etc-confd
            mountPath: /etc/glance/glance.conf.d
            readOnly: true
          - name: glance-etc
            mountPath: /etc/glance/glance-api.conf
            subPath: glance-api.conf
          - name: glance-etc
            mountPath: /etc/glance/logging.ini
            subPath: logging.ini
            readOnly: true
          resources:
            requests:
              memory: "250Mi"
              cpu: "25m"
            limits:
              memory: "250Mi"
              cpu: "100m"
{{- end }}
{{- end }}
{{- end }}
