{{- if .Values.barbican_nanny.enabled }}
{{- if .Values.barbican_nanny.db_secret_move.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: barbican-nanny
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: nanny
    component: barbican
spec:
  replicas: {{ .Values.barbican_nanny.replicas }}
  revisionHistoryLimit: {{ .Values.upgrades.revisionHistory }}
  strategy:
    type: {{ .Values.upgrades.podReplacementStrategy }}
    {{ if eq .Values.upgrades.podReplacementStrategy "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.upgrades.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.upgrades.rollingUpdate.maxSurge }}
    {{ end }}
  selector:
    matchLabels:
      app: barbican-nanny
  template:
    metadata:
      labels:
        app: barbican-nanny
        name: barbican
        alert-tier: os
        alert-service: barbican
        {{- include "utils.topology.pod_label" . | indent 8 }}
      annotations:
        chart-version: {{.Chart.Version}}
        checksum/etc-configmap.conf: {{ include (print $.Template.BasePath "/etc-configmap.yaml") . | sha256sum }}
        secrets-hash: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- if .Values.proxysql.mode }}
        prometheus.io/scrape: "true"
        prometheus.io/targets: {{ required ".Values.alerts.prometheus missing" .Values.alerts.prometheus | quote }}
        {{- end }}
        {{- include "utils.linkerd.pod_and_service_annotation" . | indent 8 }}
    spec:
      {{ include "utils.proxysql.pod_settings" . | indent 6 }}
{{- if .Values.barbican_nanny.db_secret_move.enabled }}
      containers:
      - name: db-consistency-and-purge
        image: {{ required ".Values.global.registry is missing" .Values.global.registry }}/loci-barbican:{{.Values.imageVersionbarbicanApi | default .Values.imageVersion | default .Values.image_version | required "Please set barbican.imageVersion or similar"}}
        imagePullPolicy: IfNotPresent
        command:
        - dumb-init
        - kubernetes-entrypoint
        env:
        - name: COMMAND
          value: "{{ if not .Values.barbican_nanny.debug }}/bin/bash /scripts/barbican-db-consistency-and-purge.sh{{ else }}sleep inf{{ end }}"
        - name: BARBICAN_DB_SECRET_MOVE_ENABLED
          value: {{ .Values.barbican_nanny.db_secret_move.enabled | quote }}
        - name: BARBICAN_DB_OLD_PROJECT_ID
          value: {{ .Values.barbican_nanny.db_secret_move.old_project_id | quote }}
        - name: BARBICAN_DB_NEW_PROJECT_ID
          value: {{ .Values.barbican_nanny.db_secret_move.new_project_id | quote }}
        - name: BARBICAN_NANNY_INTERVAL
          value: {{ .Values.barbican_nanny.interval | quote }}
        {{- if .Values.sentry.enabled }}
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: sentry
              key: barbican.DSN.python
        {{- end }}
        resources:
          requests:
            memory: "250Mi"
            cpu: "25m"
          limits:
            memory: "250Mi"
            cpu: "100m"
        volumeMounts:
        - name: barbican-scripts
          mountPath: /scripts/barbican-db-consistency-and-purge.sh
          subPath: barbican-db-consistency-and-purge.sh
          readOnly: true
        - name: barbican-etc
          mountPath: /etc/barbican/barbican-api.conf
          subPath: barbican-api.conf
          readOnly: true
        - name: barbican-etc
          mountPath: /etc/barbican/logging.ini
          subPath: logging.ini
          readOnly: true
        - name: barbican-etc-confd
          mountPath: /etc/barbican/barbican.conf.d
          readOnly: true
        {{- include "utils.proxysql.volume_mount" . | indent 8 }}
        {{- include "utils.trust_bundle.volume_mount" . | indent 8 }}
      {{- tuple . 1 | include "utils.proxysql.container" | indent 6 }}
      volumes:
      - name: barbican-etc
        configMap:
          name: barbican-etc
      - name: barbican-etc-confd
        secret:
          secretName: {{ .Release.Name }}-secrets
      - name: barbican-scripts
        configMap:
          name: barbican-scripts
      {{- include "utils.proxysql.volumes" . | indent 6 }}
      {{- include "utils.trust_bundle.volumes" . | indent 6 }}
{{- end }}
{{- end }}
{{- end }}
