{{- if .Values.cronus.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cronus
  namespace: {{ .Release.Namespace }}
  labels:
    app: cronus
data:
  config.yaml: {{ include "cronus/templates/cronus/_config.yaml.tpl" . | b64enc }}
{{- end -}}