{{- if .Values.cronus.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: cronus
  namespace: {{ .Release.Namespace }}
  annotations:
    cloud.sap/skip-template: "true"
  labels:
    app: cronus
    chart: cronus
    release: cronus
    heritage: {{ .Values.Release.Service }}
type: Opaque
data:
  keystonePassword: {{.Values.config.keystone.password | b64enc }}
  cronusServicePassword: {{ .Values.global.cronus_service_password | b64enc }}
  applicationCredentialSecret: {{ .Values.config.applicationCredentialSecret | b64enc }}
  rabbitmqPassword: {{.Values.rabbitmq.users.default.password }}
  rabbitmqNotificationsPassword: {{.Values.rabbitmq_notifications.users.default.password | b64enc }}
  sentryDsn: {{ .Values.cronus.sentryDsn | b64enc }}
{{- end -}}