{{- if .Values.cronus.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: cronus-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: cronus
    chart: cronus
    release: cronus
type: Opaque
data:
  sentryDsn: {{ .Values.cronus.sentryDsn | b64enc }}
  rabbitmqUser:  {{ .Values.rabbitmq.users.default.user | b64enc }}
  rabbitmqCreds: {{  `{{  resolve .Values.rabbitmq.users.default.password }}`  | b64enc }}
  rabbitmqHost:  {{ .Values.rabbitmq.host | b64enc }}
  {{- with .Values.rabbitmq_notifications }}
  {{- $user := default "" .users.default.user }}
  {{- $password := default "" .users.default.password }}
  {{- $host := printf "%s.%s.%s:5672" "hermes-rabbitmq-notifications" $.Values.global.region $.Values.global.tld }}
  {{- if $.Values.config.cronusAuditSink.host }}
    {{- $host = $.Values.config.cronusAuditSink.host }}
  {{- end }}
  rabbitmqUrl: {{ if and $user $password $host }}{{ printf "amqp://%s:%s@%s/" $user $password $host | quote | b64enc }}{{ else }}"{{ "" | b64enc }}"{{ end }}
  {{- end }}
{{- end -}}