{{- if .Values.cronus.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: cronus-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: cronus
    chart: cronus
    release: cronus
type: Opaque
data:
  sentryDsn: {{ .Values.cronus.sentryDsn | b64enc }}
  {{- $r_user := default "" .Values.rabbitmq.users.default.user }}
  {{- $r_creds := default "" .Values.rabbitmq.users.default.password }}
  {{- $r_host := default "" .Values.rabbitmq.host }}
  rabbitmqUri: {{ printf `amqp://%s:{{ resolve "%s" }}@%s/` .Values.rabbitmq.users.default.user .Values.rabbitmq.users.default.password .Values.rabbitmq.host | quote | b64enc }}
  {{- with .Values.rabbitmq_notifications }}
  {{- $user := default "" .users.default.user }}
  {{- $password := default "" .users.default.password }}
  {{- $host := printf "%s.%s.%s:5672" "hermes-rabbitmq-notifications" $.Values.global.region $.Values.global.tld }}
  {{- if $.Values.config.cronusAuditSink.host }}
    {{- $host = $.Values.config.cronusAuditSink.host }}
  {{- end }}
  rabbitmqUrl: {{ if and $user $password $host }}{{ printf "amqp://%s:%s@%s/" $user $password $host | quote | b64enc }}{{ else }}"{{ "" | b64enc }}"{{ end }}
  {{- end }}
{{- end -}}