{{- if .Values.cronus.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: cronus
  namespace: {{ .Release.Namespace }}
  annotations:
    cloud.sap/skip-template: "true"
  labels:
    app: cronus
    chart: cronus
    release: cronus
type: Opaque
data:
  applicationCredentialSecret: {{ .Values.config.applicationCredentialSecret | quote }}
  sentryDsn: {{ .Values.cronus.sentryDsn | quote }}
  {{- $r_user := .Values.rabbitmq.users.default.user }}
  {{- $r_creds := .Values.rabbitmq.users.default.password }}
  {{- $r_host := .Values.rabbitmq.host }}
  rabbitmqUri: {{ printf "amqp://%s:%s@%s/" $r_user $r_creds $r_host | quote }}
  {{- $user := .Values.rabbitmq_notifications.users.default.user }}
  {{- $password := .Values.rabbitmq_notifications.users.default.password }}
  {{- $host := printf "%s.%s.%s:5672" "hermes-rabbitmq-notifications" .Values.global.region .Values.global.tld }}
  {{- if .Values.config.cronusAuditSink.host }}
    {{- $host = .Values.config.cronusAuditSink.host }}
  {{- end }}
  AuditSinkrabbitmqUrl: {{ printf "amqp://%s:%s@%s/" $user $password $host | quote }}
{{- end -}}