{{- if .Values.nebula.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: nebula-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    cloud.sap/skip-template: "true"
  labels:
    app: nebula
    chart: nebula
    release: nebula
    heritage: {{ .Release.Service }}
type: Opaque
data:
  sentryDsn: {{ .Values.nebula.sentryDsn | b64enc }}
{{- end -}}